### ISSUE TITLE
Load pretrained weights?

### ISSUE THREAD

**Issue by zapaishchykova** [shibuiwilliam/Keras_Autoencoder#1]
Hi!
Is there anywhere I can get pretrained weights ""AutoEncoder_Cifar10_Deep_weights.05-0.56-0.56.hdf5")" ?
Thanks!

**Comment by naveenjoshii** [comment]
from keras.models import load_model
model = load_model("AutoEncoder_Cifar10_Deep_weights.05-0.56-0.56.hdf5") #you need to download this .hdf5 file and give the path to this load_model function
weights = model.load_weights

**Comment by VMBoehm** [comment]
where can I find this file for download?
